# Schema for the configuration files of the Private Taxonomy module.

private_taxonomy.settings:
  type: config_object
  label: 'Private taxonomy settings'
  mapping:
    cloning_user_name:
      type: string
      label: 'User terms to clone'
    enable_new_users:
      type: boolean
      label: 'Create default terms for new users'

taxonomy.vocabulary.*.third_party.private_taxonomy:
  type: mapping
  label: 'Mark vocabulary as private'
  mapping:
    private:
      type: integer
      label: 'Private vocabulary'

field.storage_settings.private_taxonomy_term_reference:
  type: base_entity_reference_field_settings
  label: 'Private taxonomy term reference settings'
  mapping:
    options_list_callback:
      type: string
      label: 'Options list callback'
    allowed_values:
      type: sequence
      label: 'Allowed values'
      sequence:
        - type: mapping
          label: 'Allowed values'
          mapping:
            vocabulary:
              type: string
              label: 'Vocabulary'
            users:
              type: string
              label: 'Users'

field.field_settings.private_taxonomy_term_reference:
  type: mapping
  label: 'Private taxonomy term reference settings'
  mapping:
    handler:
      type: string
      label: 'Reference method'

field.widget.settings.private_taxonomy_autocomplete:
  type: mapping
  label: "Private taxonomy autocomplete settings."
  mapping:
    size:
      type: integer
      label: 'Size'
    autocomplete_route_name:
      type: string
      label: 'Autocomplete route name'
